Don't assume /sys/class/mdev_bus exists
If this directory doesn't exist, `mdevctl types` exits with an error and
a confusing message:

    $ mdevctl types
    Error: No such file or directory (os error 2)

Just handle this error and return an empty list of types.

Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>