prevent panic when parsing attributes in JSON
Using an invalid json causes a panic if an attribute value is not of type string.

Example:
{"mdev_type": "vfio_ap-passthrough", "start": "manual", "attrs":[{"assign_adapter": 0},{"assign_domain": 4}]}

mdevctl define --parent matrix --uuid eeeeeeee-ffff-1111-2222-333333333333 --jsonfile invalid.json
thread 'main' panicked at src/mdev.rs:162:51:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Signed-off-by: Boris Fiuczynski <fiuczy@linux.ibm.com>