Handle FS permissions problems for defined devices
If there are any persistent device definition files that have permission
errors, mdevctl would issue a cryptic error message and give up. For
example, if I create a file named
/etc/mdevctl.d/test/e04b082d-5fb8-4614-b7a2-1b0c84506b4f with no read
permissions, then try to run `mdevctl list --defined` as a non-root
user, I will get the following output:

    $ mdevctl list --defined
    Error: Permission denied (os error 13)

These permission errors won't normally occur because mdevctl writes its
own configuration files. But since we now allow people to drop scripts
into /etc/mdevctl.d/scripts.d/, it's more likely that administrators
might accidentally mess something up within the mdevctl configuration
directory. So handle these sorts of failures a bit more gracefully by
continuing to list any devices that we *can* access and printing a
warning for any issues. For example, the previous scenario now results
in something like this:

    $ mdevctl list --defined
    [2021-12-03T16:31:28Z WARN  mdevctl] Unable to open file "/etc/mdevctl.d/test/e04b082d-5fb8-4614-b7a2-1b0c84506b4f": Permission denied (os error 13)
    1a343fa3-b8b5-40f8-bc3e-2c4f4830a43f 0000:00:02.0 i915-GVTg_V5_8 manual
    23c2b183-5876-40f1-90b2-5350b0a03c9b 0000:00:02.0 i915-GVTg_V5_8 manual (active)
    ad03d4f5-76ac-49a2-bd49-c01a11e43555 0000:00:02.0 i915-GVTg_V5_8 manual

Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>