Fix panic on modify delattr with invalid index
Providing the max index plus one causes a panic.

Here is an example:

$ mdevctl list -d -v
ed4654e5-12f2-4936-b079-4bba74d2c785 matrix vfio_ap-passthrough auto (active)
  Attrs:
    @{0}: {"testattr1":"testval1"}
    @{1}: {"testattr2":"testval2"}
    @{2}: {"testattr3":"testval3"}

$ mdevctl modify --delattr -i 3 -u ed4654e5-12f2-4936-b079-4bba74d2c785
thread 'main' panicked at 'removal index (is 3) should be < len (is 3)', src/mdev.rs:442:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Signed-off-by: Boris Fiuczynski <fiuczy@linux.ibm.com>