Don't assume /sys/bus/mdev directory exists
If this directory doesn't exist, `mdevctl list` will exit with an error
and print a confusing message:

    $ mdevctl list
    Error: No such file or directory (os error 2)

Handle the error and return an empty list of devices.

Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>