Report a useful error when /etc/mdevctl.d doesn't exist
Generally, the distribution package should ensure that the persistent
device definition configuration directory exists. But if it doesn't
exist, the error message is rather cryptic. It just says:
    $ mdevctl list -d
    Error: No such file or directory (os error 2)

With this change, we now get something a bit more helpful:
    $ mdevctl list -d
    Error: Required directory "/etc/mdevctl.d" doesn't exist. This may indicate a packaging or installation error

Fixes #56

Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>