environments: prevent callout error
Loading from sysfs always succeeds and data for mdev_tape might not have
been set. Without checking if the mdev is active the callout fails to
initialize with the error
Error: Device ed4654e5-12f2-4936-b079-4bba74d2c783 must have a defined mdev_type

This problem is caused by raciness between read_dir(), delayed
load_from_sysfs() calls and someone deleting mdevs. The likelihood to
catch this increases with the number of active mdevs and the amount of
time mdev_type matching callout scripts requires to complete
get:attributes callouts.

Signed-off-by: Boris Fiuczynski <fiuczy@linux.ibm.com>