Handle duplicate UUIDs with different parents
It's technically supported to have multiple defined devices with the
same UUID as long as they have different parents. Several bugs prevented
this from working properly.

https://github.com/mdevctl/mdevctl/pull/36#pullrequestreview-684844675

    Using the same uuid with different parents leads to several issues both when -p is given or not:

    Without -p

    Warnings are printed:

    # mdevctl list -d
    [2021-06-16T07:43:17Z WARN  mdevctl::mdev] Overwriting parent for mdev 8847e3d7-10f6-42d1-baab-1301bfaafad2: matrix => 0.0.26aa
    [2021-06-16T07:43:17Z WARN  mdevctl::mdev] Overwriting mdev type for mdev 8847e3d7-10f6-42d1-baab-1301bfaafad2: vfio_ap-passthrough => vfio_ccw-io
    8847e3d7-10f6-42d1-baab-1301bfaafad2 0.0.26aa vfio_ccw-io auto (active)
    8847e3d7-10f6-42d1-baab-1301bfaafad2 0.0.26aa vfio_ccw-io manual (active)

    Can't undefine devices:

    # mdevctl undefine -u 8847e3d7-10f6-42d1-baab-1301bfaafad2
    [2021-06-16T07:46:04Z WARN  mdevctl::mdev] Overwriting parent for mdev 8847e3d7-10f6-42d1-baab-1301bfaafad2: matrix => 0.0.26aa
    [2021-06-16T07:46:04Z WARN  mdevctl::mdev] Overwriting mdev type for mdev 8847e3d7-10f6-42d1-baab-1301bfaafad2: vfio_ap-passthrough => vfio_ccw-io
    Error: Failed to remove file "/etc/mdevctl.d/0.0.26aa/8847e3d7-10f6-42d1-baab-1301bfaafad2"

    Caused by:
        No such file or directory (os error 2)

    With -p

    Wrong device is listed

    # mdevctl list -d -p matrix
    [2021-06-16T09:15:30Z WARN  mdevctl::mdev] Overwriting parent for mdev 8847e3d7-10f6-42d1-baab-1301bfaafad2: matrix => 0.0.26aa
    [2021-06-16T09:15:30Z WARN  mdevctl::mdev] Overwriting mdev type for mdev 8847e3d7-10f6-42d1-baab-1301bfaafad2: vfio_ap-passthrough => vfio_ccw-io
    8847e3d7-10f6-42d1-baab-1301bfaafad2 0.0.26aa vfio_ccw-io manual (active)

    Can't undefine device

    # mdevctl undefine -p matrix -u 8847e3d7-10f6-42d1-baab-1301bfaafad2
    [2021-06-16T07:53:33Z WARN  mdevctl::mdev] Overwriting parent for mdev 8847e3d7-10f6-42d1-baab-1301bfaafad2: matrix => 0.0.26aa
    [2021-06-16T07:53:33Z WARN  mdevctl::mdev] Overwriting mdev type for mdev 8847e3d7-10f6-42d1-baab-1301bfaafad2: vfio_ap-passthrough => vfio_ccw-io
    Error: Failed to remove file "/etc/mdevctl.d/0.0.26aa/8847e3d7-10f6-42d1-baab-1301bfaafad2"

    Caused by:
        No such file or directory (os error 2)

Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>